# WELCOME TO RUACDB LOG CONFIG FILE.
# LAST UPDATE: 2026-07-20
# AUTHOR: ohmycode-cn(ohcode@163.com)

 
# [ENABLE_TERM_COMPATIBLE_MODE]
# Details:
#           If true is enabled, it means using the old ANSI sequence '\ 033', and if false is enabled, 
#         it means using the new ANSI sequence '\ x1b'.
# Supported values: true, false
# Default    value: true
#
ENABLE_TERM_COMPATIBLE_MODE="true";

# [ENABLE_TERM_HIGHLIGHT_MODE]
# Details:
#           If true is enabled, it means using the highlight mode, and if false is enabled, 
#         it means using the normal mode.
# Supported values: true, false
# Default    value: false
#
ENABLE_TERM_HIGHLIGHT_MODE="false";

# [ENABLE_TERM_BOLD_FONT_MODE]
# Details:
#           If true is enabled, it means using the bold font mode, and if false is enabled, 
#         it means using the normal mode.
# Supported values: true, false
# Default    value: false
ENABLE_TERM_BOLD_FONT_MODE="false";

# [ENABLE_TERM_LOG_PRINT_MODE]
# Details:
#           If true is enabled, it means using the log print mode, and if false is enabled, 
#         it means using the normal mode.
# Supported values: true, false
# Default    value: false
#
ENABLE_TERM_LOG_PRINT_MODE="false";



# [LOG_LEVEL_FILTER]
# Details:
#         Log level filter.
# Supported values: debug, info, warning, error, fatal
# Default    value: debug
#
LOG_TERM_LEVEL_FILTER="debug";

# [LOG_FILE_LEVEL_FILTER]
# Details:
#         Log level filter.
# Supported values: debug, info, warning, error, fatal
# Default    value: debug
#
LOG_FILE_LEVEL_FILTER="debug";

# [LOG_MIN_LEVEL_FILTER]
# Details:
#         Log min level filter.
# Supported values: debug, info, warning, error, fatal
# Default    value: debug
#
LOG_MIN_LEVEL_FILTER="debug";



# [LOG_TERM_FORMAT_MODE]
# Details:
#         Supported log format mode: text, json, xml
# Recommended: text.
# Supported values: text, json, xml
# Default    value: text
#
LOG_TERM_FORMAT_MODE="text";

# [LOG_FILE_FORMAT_MODE]
# Details:
#         Supported log format mode: text, json, xml
# Attention: Please choose according to business needs.
# Supported values: text, json, xml
# Default    value: text
#
LOG_FILE_FORMAT_MODE="text";

# [LOG_OUTPUT_MODE]
# Details:
#         Supported output mode: console, file, both(console and file)
# Supported values: console, file, both
# Default    value: console
#
LOG_OUTPUT_MODE="console";

# [LOG_WRITE_PATH]
# Details:
#         Log file path.
# Default values: /home/repox/Engineering/ruacdbv01/ruacdb/tmp
#
LOG_WRITE_PATH="/home/repox/Engineering/ruacdbv01/ruacdb/tmp";

# [LOG_WRITE_FILE]
# Details:
#         Log file name.
# Default values: ruacdb.test.log
#
LOG_WRITE_FILE="ruacdb.test.log";

# [LOG_FILE_SIZE_LIMIT]
# Details:
#         Log file size limit.
# Supported units: B: byte, KB: kilobyte, MB: megabyte, GB: gigabyte
# Default values: 128MB
#
LOG_FILE_SIZE_LIMIT="128MB";
